---
info:
  stage: dev

spring:
  application:
    name: demo-web-app

spring.boot.admin:
  url: http://localhost:8088
  client:
    metadata:
      user.name: actuator
      user.password: actuator

management.security.enabled: false

